"""users table added

Revision ID: 139483facaed
Revises: 
Create Date: 2019-10-29 14:28:29.522555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139483facaed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_name'), 'user', ['company_name'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_company_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
