"""some changes v2

Revision ID: 5e7e2602beca
Revises: ceffa3b78e83
Create Date: 2019-10-31 09:22:18.667811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7e2602beca'
down_revision = 'ceffa3b78e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_company_name', table_name='user')
    op.create_index(op.f('ix_user_company_name'), 'user', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_name'), table_name='user')
    op.create_index('ix_user_company_name', 'user', ['company_name'], unique=1)
    # ### end Alembic commands ###
