"""invoice status added

Revision ID: 860e5f0bfb21
Revises: 5e7e2602beca
Create Date: 2019-11-13 12:49:33.033409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860e5f0bfb21'
down_revision = '5e7e2602beca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('invoice_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'invoice_status')
    # ### end Alembic commands ###
