"""clients table added

Revision ID: 8d1c399df7ea
Revises: 139483facaed
Create Date: 2019-10-29 14:47:40.503779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1c399df7ea'
down_revision = '139483facaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=140), nullable=True),
    sa.Column('client_company', sa.String(length=140), nullable=True),
    sa.Column('client_email', sa.String(length=140), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
