"""tables fixed

Revision ID: ceffa3b78e83
Revises: 8d1c399df7ea
Create Date: 2019-10-29 15:06:30.298050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceffa3b78e83'
down_revision = '8d1c399df7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=140), nullable=True),
    sa.Column('client_company', sa.String(length=140), nullable=True),
    sa.Column('client_email', sa.String(length=140), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('client_company', sa.VARCHAR(length=140), nullable=True),
    sa.Column('client_email', sa.VARCHAR(length=140), nullable=True),
    sa.Column('invoice_amount', sa.INTEGER(), nullable=True),
    sa.Column('service_description', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('client')
    # ### end Alembic commands ###
